#ifndef FILESCANNING_LIB_GLOBAL_H
#define FILESCANNING_LIB_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(FILESCANNING_LIB_LIBRARY)
#define FILESCANNING_LIB_EXPORT Q_DECL_EXPORT
#else
#define FILESCANNING_LIB_EXPORT Q_DECL_IMPORT
#endif

#endif // FILESCANNING_LIB_GLOBAL_H
